portmidi: fix build on Linux
Homebrew/linuxbrew-core pull request #21320
Opened 2020-10-23 19:58 UTC by clpo13

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [X] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

Build failure logs: https://gist.github.com/5d3a50b178eb30c23598ca6af55306ac. Java is a requirement of the build, so I included openjdk as a dependency on Linux. The patch at the end ensures built files are put in the right place in the build directory, and the `inreplace` calls ensure everything gets installed into the right Homebrew directories instead of `/usr/local` or `/usr/share`, which are hardcoded in multiple places.

2020-10-23 20:58 UTC, clpo13 commented
This is being blocked by [libxcb](https://github.com/Homebrew/linuxbrew-core/pull/21320/checks?check_run_id=1299932446#step:7:1893), which isn't building because it depends on a Python package from xcb-proto that tries to import `fractions.gcd()`, which was [deprecated](https://bugs.python.org/issue39350) in favor of `math.gcd()` in Python 3.5 and finally removed in Python 3.9. The issue has already been [fixed upstream](https://gitlab.freedesktop.org/xorg/proto/xcbproto/-/commit/426ae35bee1fa0fdb8b5120b1dcd20cee6e34512).

```text
make[1]: Entering directory '/tmp/libxcb-20201023-8758-18awb29/libxcb-1.13.1/src'
/home/linuxbrew/.linuxbrew/opt/python@3.9/bin/python3 ./c_client.py	-c "libxcb 1.13.1" -l "X Version 11" \
	-s "3" -p /home/linuxbrew/.linuxbrew/Cellar/xcb-proto/1.13_1/lib/python3.9/site-packages \
	 \
	/home/linuxbrew/.linuxbrew/Cellar/xcb-proto/1.13_1/share/xcb/xproto.xml
/home/linuxbrew/.linuxbrew/opt/python@3.9/bin/python3 ./c_client.py	-c "libxcb 1.13.1" -l "X Version 11" \
	-s "3" -p /home/linuxbrew/.linuxbrew/Cellar/xcb-proto/1.13_1/lib/python3.9/site-packages \
	 \
	/home/linuxbrew/.linuxbrew/Cellar/xcb-proto/1.13_1/share/xcb/bigreq.xml

Failed to load the xcbgen Python package!
Make sure that xcb/proto installed it on your Python path.
If not, you will need to create a .pth file or define $PYTHONPATH
to extend the path.
Refer to the README file in xcb/proto for more info.

Traceback (most recent call last):
  File "/tmp/libxcb-20201023-8758-18awb29/libxcb-1.13.1/src/./c_client.py", line 3338, in <module>

Failed to load the xcbgen Python package!
Make sure that xcb/proto installed it on your Python path.
If not, you will need to create a .pth file or define $PYTHONPATH
to extend the path.
Refer to the README file in xcb/proto for more info.

Traceback (most recent call last):
  File "/tmp/libxcb-20201023-8758-18awb29/libxcb-1.13.1/src/./c_client.py", line 3338, in <module>
    from xcbgen.state import Module
  File "/home/linuxbrew/.linuxbrew/Cellar/xcb-proto/1.13_1/lib/python3.9/site-packages/xcbgen/state.py", line 7, in <module>
    from xcbgen import matcher
  File "/home/linuxbrew/.linuxbrew/Cellar/xcb-proto/1.13_1/lib/python3.9/site-packages/xcbgen/matcher.py", line 12, in <module>
    from xcbgen.xtypes import *
  File "/home/linuxbrew/.linuxbrew/Cellar/xcb-proto/1.13_1/lib/python3.9/site-packages/xcbgen/xtypes.py", line 5, in <module>
    from xcbgen.align import Alignment, AlignmentLog
  File "/home/linuxbrew/.linuxbrew/Cellar/xcb-proto/1.13_1/lib/python3.9/site-packages/xcbgen/align.py", line 5, in <module>
    from fractions import gcd
ImportError: cannot import name 'gcd' from 'fractions' (/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/fractions.py)
    from xcbgen.state import Module
  File "/home/linuxbrew/.linuxbrew/Cellar/xcb-proto/1.13_1/lib/python3.9/site-packages/xcbgen/state.py", line 7, in <module>
    from xcbgen import matcher
  File "/home/linuxbrew/.linuxbrew/Cellar/xcb-proto/1.13_1/lib/python3.9/site-packages/xcbgen/matcher.py", line 12, in <module>
    from xcbgen.xtypes import *
  File "/home/linuxbrew/.linuxbrew/Cellar/xcb-proto/1.13_1/lib/python3.9/site-packages/xcbgen/xtypes.py", line 5, in <module>
    from xcbgen.align import Alignment, AlignmentLog
  File "/home/linuxbrew/.linuxbrew/Cellar/xcb-proto/1.13_1/lib/python3.9/site-packages/xcbgen/align.py", line 5, in <module>
    from fractions import gcd
ImportError: cannot import name 'gcd' from 'fractions' (/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/fractions.py)
Makefile:1407: recipe for target 'bigreq.c' failed
make[1]: *** [bigreq.c] Error 1
```

2020-10-29 11:17 UTC, iMichka commented on Formula/portmidi.rb
> -  revision 2
No need to bump the revision as we did not have a bottle previously.

2020-10-29 11:18 UTC, iMichka commented on Formula/portmidi.rb
> +  patch :DATA unless OS.mac?
Has this patch been submitted to portmedia ?

2020-10-29 11:21 UTC, iMichka requested changes
I made two comments to start with.

Do you know why java is needed on linux but not on Mac?

2020-10-29 15:31 UTC, clpo13 commented on Formula/portmidi.rb
> +  patch :DATA unless OS.mac?
I'll suggest it. There hasn't been a portmidi release since 2010, though it looks like there's some recent development on the project as a whole. The working directory problem has already been [fixed](https://sourceforge.net/p/portmedia/code/230/), but I don't think the CMAKE_CACHEFILE_DIR one has.

2020-10-29 15:53 UTC, clpo13 commented
The build requires Java on both, but macOS (recent versions at least) comes with a pre-installed JDK that has symlinks in `/usr/bin`, so there will always be `java` and `javac` commands on the path.

2020-10-30 08:40 UTC, iMichka commented
I see. What we are trying to do on Mac is to use as much as possible our openjdk formula.

Ideally, we should port the Mac formula to use our openjdk first, and keep the linux-only changes here.

Do you think you could open a PR at https://github.com/Homebrew/homebrew-core first, to migrate the formula to openjdk there? Sorry if there is some back and forth right now, but all the changes made in this linux repo will be bacported to Mac, so I prefer to make as many changes as possibles in the Mac repo first, to avoid to have to back port too much stuff in the long run.

2020-11-02 20:21 UTC, clpo13 commented
Actually, I was mistaken. Java is only used on macOS when building the pmdefaults target (`make -f pm_mac/Makefile.osx pmdefaults`), which the formula doesn't do. On Linux, pmdefaults is always built, which is why Java is required there.

I did find that building portmidi using the latest portmedia snapshot (r234) meant the SDKROOT and SYSROOT fixes in the macOS install instructions were unnecessary, and it would make the `pm_java/CMakeLists.txt` changes in the Linux patch above unnecessary as well.

2020-12-05 00:06 UTC, closed without merging