Fix jabba.rb formula
Homebrew/linuxbrew-core pull request #21609
Opened 2020-11-24 17:26 UTC by michaelcusick

- [ X ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ X ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ X ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ X ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ X ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ NO ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

The jabba.rb formula installs without error, but doesn't work. This PR fixes that issue. A similar PR will be opened on homebrew-core.

2020-11-26 22:06 UTC, iMichka requested changes
Hi. Thanks for working on this. I made a few comments

2020-11-26 22:06 UTC, iMichka commented on Formula/jabba.rb
> +    sha256 "9a971099c0ab85804166dbf96b99653f37cc8095749df982d346ee397c8f9cd5" => :amd64_linux
Don't modify the Mac bottles lines.

Just remove the linux bottle she, that's enough.

2020-11-26 22:06 UTC, iMichka commented on Formula/jabba.rb
> +  revision 1
revision 1 unless OS.mac?

2020-11-26 22:06 UTC, iMichka commented on Formula/jabba.rb
> +    mkdir("$HOME/.jabba")
Do you know why this is not needed on Mac?
Why are we installing something to the users home folder?

2020-11-29 00:57 UTC, michaelcusick commented
Good questions. I opened this PR too hastily. Let me check back with the author of jabba to see what needs to be done to fix the brew packages. Right now jabba doesn't work on Mac or Linux when installed with brew because it is missing some shell scripts. When using the shell script installer, those scripts get installed to `$HOME/.jabba`. I'm probably not doing this correctly. Apologies.

2020-11-29 00:57 UTC, closed without merging